services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: creddypens
    ports:
      - "5433:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - creddypens_db:/var/lib/postgresql/data
volumes:
  creddypens_db:
